name: release Project

on:
   push:
      branches:
         - main
         - david
      paths:
         - CHANGELOG.md
   workflow_dispatch:

jobs:
   release:
     uses: davidgamero/action-release-workflows/.github/workflows/release_js_project.yaml@v-prefix
     with:
         changelogPath: ./CHANGELOG.md
